# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build & Release macOS App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Set deployment target and code signing
        run: |
          # 更新部署目标版本到15.2
          /usr/libexec/PlistBuddy -c "Set :objects:2889E16B2E1CEEE500A6360B:buildSettings:MACOSX_DEPLOYMENT_TARGET 15.2" Base64_Encoder_Decoder.xcodeproj/project.pbxproj
          /usr/libexec/PlistBuddy -c "Set :objects:2889E16C2E1CEEE500A6360B:buildSettings:MACOSX_DEPLOYMENT_TARGET 15.2" Base64_Encoder_Decoder.xcodeproj/project.pbxproj
          
          # 禁用代码签名
          /usr/libexec/PlistBuddy -c "Set :objects:2889E16E2E1CEEE500A6360B:buildSettings:CODE_SIGN_IDENTITY -" Base64_Encoder_Decoder.xcodeproj/project.pbxproj
          /usr/libexec/PlistBuddy -c "Set :objects:2889E16E2E1CEEE500A6360B:buildSettings:CODE_SIGNING_REQUIRED NO" Base64_Encoder_Decoder.xcodeproj/project.pbxproj
          /usr/libexec/PlistBuddy -c "Set :objects:2889E16E2E1CEEE500A6360B:buildSettings:CODE_SIGNING_ALLOWED NO" Base64_Encoder_Decoder.xcodeproj/project.pbxproj

      - name: Build app for release
        run: |
          xcodebuild -scheme Base64_Encoder_Decoder -project Base64_Encoder_Decoder.xcodeproj -configuration Release -derivedDataPath build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      - name: Create .zip of app
        run: |
          cd build/Build/Products/Release
          zip -r Base64_Encoder_Decoder.zip Base64_Encoder_Decoder.app
          mv Base64_Encoder_Decoder.zip $GITHUB_WORKSPACE

      - name: Create DMG
        run: |
          # 创建临时目录用于构建DMG
          mkdir -p dmg_temp
          
          # 复制应用到临时目录
          cp -R build/Build/Products/Release/Base64_Encoder_Decoder.app dmg_temp/
          
          # 创建DMG
          hdiutil create -volname "Base64 Encoder Decoder" \
            -srcfolder dmg_temp \
            -ov -format UDZO \
            Base64_Encoder_Decoder.dmg
          
          # 清理临时目录
          rm -rf dmg_temp

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Base64_Encoder_Decoder.zip
            Base64_Encoder_Decoder.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
